services:
  postgres:
    image: postgres:15.5-alpine
    env_file:
      - postgres-env.properties
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-env.properties:/postgres-env.properties
      - ./script:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --user $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
